name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "914cfb69-2df7-41e0-bd57-4820b0db49b6"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "125ffa17410f4898b4e401a57c031839"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
